---
abstract: 'A POE component that implements an RFC 977 NNTP client.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
  Test::POE::Server::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Client-NNTP
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Client::NNTP:
    file: lib/POE/Component/Client/NNTP.pm
    version: 2.12
  POE::Component::Client::NNTP::Constants:
    file: lib/POE/Component/Client/NNTP/Constants.pm
    version: 2.12
requires:
  POE: 0.9999
  POE::Component::Pluggable: 0.03
  POE::Component::Pluggable::Constants: 0
  POE::Driver::SysRW: 0
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-client-nntp/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-client-nntp.git
version: 2.12
