# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-NNTP
version:      1.03
version_from: lib/POE/Component/Client/NNTP.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.31
    Socket:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
